# set variable
VCS_RTL1_CMD = vcs -R -sverilog tb.sv -debug_access+all -full64 +define+FSDB+p1 +neg_tchk
VCS_RTL1_PLOT_CMD = vcs -R -sverilog tb.sv -debug_access+all -full64 +define+FSDB+plot+p1 +neg_tchk
VCS_RTL1_COLOR_CMD = vcs -R -sverilog tb.sv -debug_access+all -full64 +define+FSDB+plot+color+p1 +neg_tchk
VCS_SYN1_CMD = vcs -R -sverilog tb.sv -debug_access+all -full64 +define+FSDB+syn+p1 +neg_tchk
VCS_SYN1_PLOT_CMD = vcs -R -sverilog tb.sv -debug_access+all -full64 +define+FSDB+plot+syn+p1 +neg_tchk
VCS_SYN1_COLOR_CMD = vcs -R -sverilog tb.sv -debug_access+all -full64 +define+FSDB+plot+color+syn+p1 +neg_tchk

VCS_RTL2_CMD = vcs -R -sverilog tb.sv -debug_access+all -full64 +define+FSDB+p2 +neg_tchk
VCS_RTL2_PLOT_CMD = vcs -R -sverilog tb.sv -debug_access+all -full64 +define+FSDB+plot+p2 +neg_tchk
VCS_RTL2_COLOR_CMD = vcs -R -sverilog tb.sv -debug_access+all -full64 +define+FSDB+plot+color+p2 +neg_tchk
VCS_SYN2_CMD = vcs -R -sverilog tb.sv -debug_access+all -full64 +define+FSDB+syn+p2 +neg_tchk
VCS_SYN2_PLOT_CMD = vcs -R -sverilog tb.sv -debug_access+all -full64 +define+FSDB+plot+syn+p2 +neg_tchk
VCS_SYN2_COLOR_CMD = vcs -R -sverilog tb.sv -debug_access+all -full64 +define+FSDB+plot+color+syn+p2 +neg_tchk

VCS_RTL3_CMD = vcs -R -sverilog tb.sv -debug_access+all -full64 +define+FSDB+p3 +neg_tchk
VCS_RTL3_PLOT_CMD = vcs -R -sverilog tb.sv -debug_access+all -full64 +define+FSDB+plot+p3 +neg_tchk
VCS_RTL3_COLOR_CMD = vcs -R -sverilog tb.sv -debug_access+all -full64 +define+FSDB+plot+color+p3 +neg_tchk
VCS_SYN3_CMD = vcs -R -sverilog tb.sv -debug_access+all -full64 +define+FSDB+syn+p3 +neg_tchk
VCS_SYN3_PLOT_CMD = vcs -R -sverilog tb.sv -debug_access+all -full64 +define+FSDB+plot+syn+p3 +neg_tchk
VCS_SYN3_COLOR_CMD = vcs -R -sverilog tb.sv -debug_access+all -full64 +define+FSDB+plot+color+syn+p3 +neg_tchk

VCS_RTL4_CMD = vcs -R -sverilog tb.sv -debug_access+all -full64 +define+FSDB+p4 +neg_tchk
VCS_RTL4_PLOT_CMD = vcs -R -sverilog tb.sv -debug_access+all -full64 +define+FSDB+plot+p4 +neg_tchk
VCS_RTL4_COLOR_CMD = vcs -R -sverilog tb.sv -debug_access+all -full64 +define+FSDB+plot+color+p4 +neg_tchk
VCS_SYN4_CMD = vcs -R -sverilog tb.sv -debug_access+all -full64 +define+FSDB+syn+p4 +neg_tchk
VCS_SYN4_PLOT_CMD = vcs -R -sverilog tb.sv -debug_access+all -full64 +define+FSDB+plot+syn+p4 +neg_tchk
VCS_SYN4_COLOR_CMD = vcs -R -sverilog tb.sv -debug_access+all -full64 +define+FSDB+plot+color+syn+p4 +neg_tchk

VCS_RTL5_CMD = vcs -R -sverilog tb.sv -debug_access+all -full64 +define+FSDB+p5 +neg_tchk
VCS_RTL5_PLOT_CMD = vcs -R -sverilog tb.sv -debug_access+all -full64 +define+FSDB+plot+p5 +neg_tchk
VCS_RTL5_COLOR_CMD = vcs -R -sverilog tb.sv -debug_access+all -full64 +define+FSDB+plot+color+p5 +neg_tchk
VCS_SYN5_CMD = vcs -R -sverilog tb.sv -debug_access+all -full64 +define+FSDB+syn+p5 +neg_tchk
VCS_SYN5_PLOT_CMD = vcs -R -sverilog tb.sv -debug_access+all -full64 +define+FSDB+plot+syn+p5 +neg_tchk
VCS_SYN5_COLOR_CMD = vcs -R -sverilog tb.sv -debug_access+all -full64 +define+FSDB+plot+color+syn+p5 +neg_tchk

VCS_RTL6_CMD = vcs -R -sverilog tb.sv -debug_access+all -full64 +define+FSDB+p6 +neg_tchk
VCS_RTL6_PLOT_CMD = vcs -R -sverilog tb.sv -debug_access+all -full64 +define+FSDB+plot+p6 +neg_tchk
VCS_RTL6_COLOR_CMD = vcs -R -sverilog tb.sv -debug_access+all -full64 +define+FSDB+plot+color+p6 +neg_tchk
VCS_SYN6_CMD = vcs -R -sverilog tb.sv -debug_access+all -full64 +define+FSDB+syn+p6 +neg_tchk
VCS_SYN6_PLOT_CMD = vcs -R -sverilog tb.sv -debug_access+all -full64 +define+FSDB+plot+syn+p6 +neg_tchk
VCS_SYN6_COLOR_CMD = vcs -R -sverilog tb.sv -debug_access+all -full64 +define+FSDB+plot+color+syn+p6 +neg_tchk

FSDB_FILE = bicubic.fsdb
LINT_SCRIPT = superlint.tcl

# simulation
rtl1:
	$(VCS_RTL1_CMD)
rtl1_plot:
	$(VCS_RTL1_PLOT_CMD)
rtl1_color:
	$(VCS_RTL1_COLOR_CMD)

rtl2:
	$(VCS_RTL2_CMD)
rtl2_plot:
	$(VCS_RTL2_PLOT_CMD)
rtl2_color:
	$(VCS_RTL2_COLOR_CMD)

rtl3:
	$(VCS_RTL3_CMD)
rtl3_plot:
	$(VCS_RTL3_PLOT_CMD)
rtl3_color:
	$(VCS_RTL3_COLOR_CMD)

rtl4:
	$(VCS_RTL4_CMD)
rtl4_plot:
	$(VCS_RTL4_PLOT_CMD)
rtl4_color:
	$(VCS_RTL4_COLOR_CMD)

rtl5:
	$(VCS_RTL5_CMD)
rtl5_plot:		
	$(VCS_RTL5_PLOT_CMD)
rtl5_color:
	$(VCS_RTL5_COLOR_CMD)

rtl6:
	$(VCS_RTL6_CMD)
rtl6_plot:
	$(VCS_RTL6_PLOT_CMD)
rtl6_color:
	$(VCS_RTL6_COLOR_CMD)

# open FSDB
nWave:
	nWave -ssf $(FSDB_FILE) &

# superlint
superlint:
	jg -superlint $(LINT_SCRIPT) &

# synthesize
syn1:
	$(VCS_SYN1_CMD)
syn1_plot:
	$(VCS_SYN1_PLOT_CMD)
syn1_color:
	$(VCS_SYN1_COLOR_CMD)

syn2:
	$(VCS_SYN2_CMD)
syn2_plot:
	$(VCS_SYN2_PLOT_CMD)
syn2_color:
	$(VCS_SYN2_COLOR_CMD)

syn3:
	$(VCS_SYN3_CMD)
syn3_plot:
	$(VCS_SYN3_PLOT_CMD)
syn3_color:
	$(VCS_SYN3_COLOR_CMD)

syn4:
	$(VCS_SYN4_CMD)
syn4_plot:
	$(VCS_SYN4_PLOT_CMD)
syn4_color:
	$(VCS_SYN4_COLOR_CMD)

syn5:
	$(VCS_SYN5_CMD)
syn5_plot:
	$(VCS_SYN5_PLOT_CMD)
syn5_color:
	$(VCS_SYN5_COLOR_CMD)

syn6:
	$(VCS_SYN6_CMD)
syn6_plot:
	$(VCS_SYN6_PLOT_CMD)
syn6_color:
	$(VCS_SYN6_COLOR_CMD)


# clean simulation result
clean:
	rm -rf *.log \
	       *.fsdb \
	       *.vpd \
	       csrc \
	       jgproject \
	       simv* \
	       daidir\
	       ucli.key\
